# https://github.com/Weilbyte/PVEDiscordDark/issues/38
- name: "Create {{ theme_basedir }} if it does not exist"
  file:
    path: "{{ theme_basedir }}"
    state: directory
    mode: 0755

- name: Check for New/Updated {{ theme_name }} components
  get_url:
    url: "{{ item }}"
    dest: "{{ theme_basedir }}/{{ item | basename }}"
    mode: 0554
  register: theme_updated
  loop:
    - "{{ theme_repo }}/{{ theme_version }}/{{ theme_name }}.sh"
    - "{{ theme_repo }}/{{ theme_version }}/{{ theme_name }}/sass/{{ theme_name }}.css"
    - "{{ theme_repo }}/{{ theme_version }}/{{ theme_name }}/js/{{ theme_name }}.js"

- name: "Install/Update {{ theme_name }}"
  block:
  - name: Check if theme is installed
    stat:
      path: /usr/share/pve-manager/css/dd_style.css
    register: theme_installed

  - name: uninstall old theme
    command: bash {{ theme_basedir }}/{{ theme_name }}.sh uninstall
    when: theme_installed.stat.exists

  - name: install new theme
    command: bash {{ theme_basedir }}/{{ theme_name }}.sh install

  when: theme_updated.changed
